import NavBar from '@/components/NavBar'
import styles from '../styles/layout.module.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const titnav = 'Orantes';
  const links = [
  
    { id: 1, url: '/', text: 'Informacion' },
    { id: 2, url: '/', text: 'Servicios' },
    { id: 3, url: '/', text: 'Trabajos' },
    { id: 4, url: '/', text: 'Contacto' },
    
    
  ];
  return (
    <html lang="es-MX">
      <body className={styles.body}>
      <NavBar titnav={titnav} links={links}/>
      {children}
      </body>
     
    </html>
  )
}
